info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of the server.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Show the status of the server.
      tags:
      - health
swagger: "2.0"
